version: '3.4'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ~/postgres/app/:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: db
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    container_name: redis

  app:
    image: app
    container_name: app
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: bash run.sh

  testing:
    image: app
    container_name: testing
    command: python manage.py test 
    depends_on:
      - app
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
  
  worker:
    depends_on:
      - app
      - redis
    command: celery -A core worker -l INFO -B
    image: app
    volumes:
      - type: bind
        source: .
        target: /app
    container_name: worker
